name: Deploy Quartz to GH Pages

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  quartz_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: yarn
      - run: yarn build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.chaoticgood.computer
