name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
            resume.cls
      - name: Upload PDF
        uses: actions/upload-release-asset@v2
        with:
          name: PDF
          path: main.pdf
